### ISSUE TITLE
Test and get ready DVWebloader

### ISSUE THREAD

**Issue by philippconzett** [DataverseNO/docker.dataverse.no#10]
Could someone install DVWebloader as a dataset-level explore tool on our docker.dataverse.no test instance in Azure cloud? See more information in this GDCC GitHub repo: [https://github.com/gdcc/dvwebloader](https://github.com/gdcc/dvwebloader). Thanks!

**Comment by philippconzett** [comment]
A little bit more background: We need this tool/functionality to make it possible for depositors to retain the folder structure of their data when they upload data directly to S3, which will be the default in DataverseNO once we have migrated to the cloud. UiT has sponsored GDCC to develop this tool/DVWebloder. I have tested a previous version. The new version on GitHub (see link above) must be installed as a dataset-level explore tool. In order to test the tool, please install it on our docker.dataverse.no test instance in Azure cloud. Thanks!

**Comment by philippconzett** [comment]
For even more background information, see this discussion thread in the Google group: [https://groups.google.com/u/1/g/dataverse-community/c/U3G6H4-fNYk](https://groups.google.com/u/1/g/dataverse-community/c/U3G6H4-fNYk)

**Comment by philippconzett** [comment]
@4tikhonov @Louis-wr @oodu 
Let me briefly recap our discussion we had yesterday: The idea of the DVWebloader tool is that depositors can upload a folder with subfolders to S3, and the subfolder structure will be retained as METADATA in Dataverse (see the metadata field "File Path" at file level. Thus the same behavior as uploading a zip file to local server. For an existing example, see [https://doi.org/10.18710/PDCLAS](https://doi.org/10.18710/PDCLAS). Click on Tree view to see the folder structure:

![image](https://user-images.githubusercontent.com/21955790/192938033-c32f798e-20a1-4a79-8748-02a95e492965.png)

and click into one of the files, and then select the Metadata tab, and scroll down to see the field File Path:

![image](https://user-images.githubusercontent.com/21955790/192938306-15791fac-2bbf-40d1-a41d-38dcbb73cccb.png)


Thus, the idea is NOT that folder structure is created in the very S3 storage. In the storage facility, the files will just be listed in flat structure, as is the case today.

Jim has now updated the instructions for how to install and run DVWebloader; see [https://github.com/gdcc/dvwebloader](https://github.com/gdcc/dvwebloader). Please give it another try! Thanks!

**Comment by philippconzett** [comment]
The tool seems now to work reasonable well. Now, we should discuss next steps. I agreed with Jim to create a Google doc to get together a prioritized list of changes. I have posted the link to the document in Teams.

**Comment by philippconzett** [comment]
The DVWebloader allows users to **upload** to S3 folders and files and the folder structure will be kept as metadata; basically the same way folder structure is kept through zip upload to local storage.

Similarly, we need a functionality/feature that allows users to keep the folder structure when **downloading** files directly from S3. When downloading from local storage, this is done by packing the files and folder metadata into a zip file. This zipping is done by passing the files from S3 through Payara. For large files, this is not feasible, because it would potentially cause the same capacity issues we have been experiencing in our local installation. That's why this kind of zip support is not possible when direct S3 download is configured.

To make it possible to retain folder structure, Jim has suggested an approach using tar files. Maybe it would also be possible to use uncompressed zip files; see the discussion thread from 2022-11-14 in Dataverse Slack # general channel. I guess for Windows users, uncompressed zip is preferred over tar?

**Comment by philippconzett** [comment]
@Louis-wr @4tikhonov:  Jim has done some improvements to the DVWebloader, among other things replaced the tar approach with zip - as requested. This is now ready for testing. Here are some instructions from Jim:

Setting up to test it basically means deploying the branch of Dataverse in the PR: [https://github.com/IQSS/dataverse/pull/9245](https://github.com/IQSS/dataverse/pull/9245).

Could you set up a Dataverse test instance following these instructions, so that we can test the update? Thanks!

**Comment by Louis-wr** [comment]
updated

**Comment by philippconzett** [comment]
Done.
