### ISSUE TITLE
Error when trying to create a dataset draft

### ISSUE THREAD

**Issue by philippconzett** [DataverseNO/docker.dataverse.no#12]
I get the following messages when trying to create a dataset draft in test-docker.dataverse.no:

Error – The dataset could not be created. If you believe this is an error, please contact [DataverseNO Support](https://test-docker.dataverse.no/dataset.xhtml?persistentId=doi%3A10.21337%2FTBS5HY&version=DRAFT#) for assistance.

Page Not Found - The page you are looking for was not found. If you believe this is an error, please contact [DataverseNO Support](https://test-docker.dataverse.no/dataset.xhtml?persistentId=doi%3A10.21337%2FTBS5HY&version=DRAFT#) for assistance.

**Comment by philippconzett** [comment]
I now was able to delete this dataset(draft). Did you do anything with the installation? Will it always be the case that deleting large dataset draft first will trigger error messages, not been deleted, and only after a few days it will be possible to delete them? @4tikhonov @Louis-wr @oodu

**Comment by Louis-wr** [comment]
This was caused by "/" becoming full and breaking dataverse
