### ISSUE TITLE
Set :ZipUploadFilesLimit to 1 AFTER login is disabled in local installation

### ISSUE THREAD

**Issue by philippconzett** [DataverseNO/docker.dataverse.no#24]
AFTER login in local installation [dataverse.no](http://dataverse.no/) has been disabled, but BEFORE we go live with cloud migrated DataverseNO: Set :ZipUploadFilesLimit to 1 to prevent traditional zip upload through API:

curl -X PUT -d 1 http://localhost:8080/api/admin/settings/:ZipUploadFilesLimit

**Comment by oodu** [comment]
curl -X PUT -d 1 http://localhost:8080/api/admin/settings/:ZipUploadFilesLimit is enabled at local prod (dataverse.no)
