### ISSUE TITLE
Depositor was not granted Contributor role for dataset draft

### ISSUE THREAD

**Issue by philippconzett** [DataverseNO/docker.dataverse.no#32]
When a depositor creates a dataset draft, s/he is automatically granted the Contributor role for that dataset draft.
For an example of how this looks like, see dataset [https://dataverse.no/dataset.xhtml?persistentId=doi:10.18710/SKT2FA](https://dataverse.no/dataset.xhtml?persistentId=doi:10.18710/SKT2FA). To see the role assignment, click on _Edit Dataset_, select _Permissions_ and _Dataset_. The depositor is listed with the Contributor role.

However, this automatic role assignment did not happen in the dataset [https://dataverse.no/dataset.xhtml?persistentId=doi:10.18710/YUG9V0&version=DRAFT](https://dataverse.no/dataset.xhtml?persistentId=doi:10.18710/YUG9V0&version=DRAFT). This dataset draft was created on April 4, 2023 at 14:16 CEST.

**Comment by Louis-wr** [comment]
Is this something that append multiple time or just the once? '
Was this successful with other depositor?

**Comment by philippconzett** [comment]
As far as I can see, this happened so far only once. I have now granted the access role manually. But it would be good to figure out why this happened. Can the Dataverse/Azure/firewall logs tell anything?

**Comment by rolfande** [comment]
I can't find any traces in the logs indicating block of this activity. For better to search the logs it would also be good to have the clientIP from where this request came from. If this was an automatic process it could be that it's not generating traffic in the firewall and rather is a internal application process.

**Comment by philippconzett** [comment]
Haven't got similar requests.
