### ISSUE TITLE
Error when trying to log in with Feide

### ISSUE THREAD

**Issue by philippconzett** [DataverseNO/docker.dataverse.no#37]
I tried to log in to dataverse.no with Feide on April 13, 2023 at 16:03 from the IP address added in Teams, and got the following error message:

> Unhandled exception
> An unhandled exception was thrown.
> 
> If you report this error, please also report this tracking number which makes it possible to locate your session in the logs available to the system administrator:
> 
> Tracking number:
> f9156a6688
> 

@Louis-wr @rolfande Any idea why this happened?

**Comment by Louis-wr** [comment]
Temporary uninett glitch.
